config/routes.rb
TrygSite::Application.routes.draw do
  root to: 'scholarish#home'

  match '/publications', to: 'scholarish#publications'
  match '/books', to: 'scholarish#books'
  match '/powerwithoutvictory', to: 'scholarish#powerwithoutvictory'
  match '/media', to: 'scholarish#media'
  match '/cv', to: 'scholarish#cv'
  match '/bio', to: 'scholarish#bio'
  match 'contact', to: 'scholarish#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/scholarish_controller.rb
class ScholarishController < ApplicationController
  def home
  end

  def publications
  end

  def books
  end

  def powerwithoutvictory
  end

  def media
  end

  def cv
  end

  def bio
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
#returns the full title on a per page basis
	def full_title(page_title)
		base_title = "Trygve Throntveit"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/scholarish_helper.rb
module ScholarishHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title><%= full_title(yield(:title)) %></title>
  <meta name="keywords" content="Trygve, Throntveit, Trygve Throntveit, Woodrow, Wilson, Woodrow Wilson" />
  <meta name="description" content="The personal homepage for Trygve Throntveit, historian and Ph.D."/>
  <meta name="rating" content="General" />
  <meta name="ROBOTS" content="ALL" />
  <%= stylesheet_link_tag    "application", media: "all" %>
  <link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,400italic|Josefin+Sans:100,300,600|Josefin+Slab:100,300,600|Vollkorn:400italic,400' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
<div class="navbar_background">
	<div class="container_12">		
		<div class="grid_3 push_1">
			<p id="main_logo"><a href="/">Trygve Throntveit</a></p>
		</div>
		<div class="navbar push_1 grid_7 align_right">
			<ul>
				<li class="nav"><%= link_to "Publications", publications_path %></li>
				<li class="nav"><%= link_to "Books", books_path %></li>
				<li class="nav"><%= link_to "Media", media_path %></li>
				<li class="nav"><%= link_to "CV", cv_path %></li>
				<li class="nav"><%= link_to "Bio", bio_path %></li>
				<li class="nav"><a href="mailto:trygve@trygve.com">Contact</a></li>
				<!-- Need to figure out how to work in the id="current_selection" -->
			</ul>
		</div>
	</div>
</div>

<%= yield %>

</body>
</html>

app/views/scholarish/bio.html.erb
<% provide(:title, "Bio") %>
<div class="container_12">	
		
<div class="grid_12 spacer">
</div>

<div class="grid_10 push_1">
	<h1 id="front_page_image">LOREM</h1>
</div>
		
<div class="clear">
</div>
<!-- Sales text -->
<div class="grid_10 push_1 bio_sales_text">
	<p>
		LOREM
	</p>
</div>
		
	<div class="clear">
	</div>

	<div class="grid_12 spacer">
	</div>			

	<div class="footer grid_12"
	></div>
</div>

app/views/scholarish/books.html.erb
<% provide(:title, "Books") %>

<div class="clear"></div>

<!-- Book Bar -->
		
<div class="grid_10 push_1">
<!-- 			<hr id="book_spacer" /> -->
	<ul class="book_nav">
		<li><a href="#" id="current_selection">William James's Ethical Republic</a></li>
		<li><%= link_to "Power Without Victory", powerwithoutvictory_path %></li>
	</ul>
	<hr id="book_spacer" />
</div>
		
<div class="clear">
</div>

<div class="grid_6 push_1">
	
	<div class="grid_6 alpha">
		<p class="buy_book"><a>Buy the Book</a></p>
	</div>
	
	<div class="book_title grid_6 alpha">
		<p>William James&rsquo;s Ethical Republic</p>
	</div>
			
	<div class="book_subhead grid_6 alpha">
		<p>A moral and political study</p>
	</div>

	<div class="book_first_paragraph grid_6 alpha">
		<p>William James&rsquo;s Ethical Republic provides the first comprehensive treatment of William James&rsquo;s ethical philosophy, including its origins, content, context, and legacies.</p>
	</div>
			
	<div class="book_description grid_6 alpha">
		<p>Unlike most studies of James, this book also examines his political thought in relation to his ethics, demonstrating their mutual coherence as well as their continuity with James&rsquo;s pragmatist epistemology and radical-empiricist metaphysics. In the process it accomplishes three goals that have not yet been achieved in any single work on James.</p>

		<p>First, by putting James&rsquo;s moral philosophy in consistent dialogue with his epistemology and metaphysics, it demonstrates the coherence and robustness of his pragmatist ethics in the absence of a deity or deontological claims, without discounting his theistic leanings and belief in the moral value of faith in a supernatural order. Second, it analyzes James&rsquo;s extension of his ethics to political questions, both theoretical and topical, involving both domestic issues and world affairs. It thus situates James in his historical moment and clarifies his contribution to what we now call democratic theory, as well as to an internationalist discourse that reached its apex during World War I. Third, it reintroduces James himself into contemporary debates over the content and applications of a pragmatist ethics, giving special attention to the potential value of a pragmatist approach to American politics and international affairs, while affirming its relevance to any society aspiring to more democratic relations among its citizens or with its neighbors.</p>

		<p>William James&rsquo;s Ethical Republic will appeal particularly to James scholars, American intellectual and cultural historians, and philosophers and cultural critics, especially those interested in the contemporary revival of pragmatism. The book is under contract with Palgrave Macmillan and the manuscript is scheduled for delivery in 2012.</p>
	</div>

</div>

<div class="grid_4 push_1">

	<div class="grid_4 alpha">
		<h2 class="book_picture">William James</h2>
	</div>
		
		<div class="pull_quote grid_4 alpha">
<!-- 				<p>&ldquo;LOREM&rdquo;</p> -->
		</div>
		
		<div class="pull_quote_author grid_4 alpha">
<!-- 				<p>- LOREM</p> -->
		</div>			
		
	</div>
		
	<div class="footer grid_12">
	</div>
	
</div>

app/views/scholarish/contact.html.erb
<% provide(:title, "Contact") %>
<div class="container_12">	
		
	<div class="grid_12 spacer">
	</div>

	<div class="grid_10 push_1">
		<h1 id="front_page_image">LOREM</h1>
	</div>
		
	<div class="clear">
	</div>
		<!-- Sales text -->
	<div class="grid_10 push_1 bio_sales_text">
		<p>LOREM</p>
	</div>
		
	<div class="clear">
	</div>

	<div class="grid_12 spacer">
	</div>			

	<div class="footer grid_12">
	</div>
</div>

app/views/scholarish/home.html.erb
<% provide(:title, "Home") %>
<div class="container_12">	
<!-- Placeholder text for frontpage image -->
		
	<div class="grid_12 spacer"></div>

		
	<div class="grid_3 push_1 front_page_image_container">
		<h1 id="front_page_image">Tryg</h1>
	</div>
		<!-- Sales text -->
	<div id="sales_text" class="grid_7 push_1">
		<p>Hi! I&rsquo;m a lecturer and assistant director of Undergraduate Studies at Harvard University. I&rsquo;m currently working on <%= link_to "two projects", books_path %></a>. The first is a book for the University of Chicago Press called <%= link_to "Power Without Victory", powerwithoutvictory_path %>, exploring Woodrow Wilson&rsquo;s forgotten contributions to American power. I&rsquo;m also working on a book about <%= link_to "William James", books_path %>. Learn more <%= link_to "here", bio_path %>.</p>
	</div>
		
	<div class="clear"></div>
		
	<div class="grid_12 spacer"></div>
	
		
	<div class="container_12 grid_12">
		<!-- Sales and Special Project Boxes. The popover class is for mouseover events. -->
		<div id="box_01" class="grid_4 push_1 sales_box">
			<hr />
			<h2><a>William James</a></h2>
			<p>LOREM</p>
				<!--
<div class="popover">
					<a href="/williamjames">
					<h3>William James</h3>
					<p>LOREM</p>
					</a>
				</div>
-->
			<hr />

		</div>
			
			
			
		<div id="box_02" class="grid_4 push_3 sales_box">
			<hr />
			<h2><a>Power Without Victory</a></h2>
			<p>LOREM</p>
				<!--
<div class="popover">
					<a href="/powerwithoutvictory">
					<h3>Power Without Victory</h3>
					<p>LOREM</p>
					</a>
				</div>
-->
			<hr />



		</div>
	</div>	
	<div></div>
		
	</div>
</div>

app/views/scholarish/media.html.erb
<% provide(:title, "Media") %>
<div class="container_12">	

	<div class="clear"></div>


		<!-- Sales Pitch. I think every page should have one, the publications one should reflect in greater detail what the authors write -->

	<div class="push_4 grid_7">
		<h2 class="page_title">Media</h2>
	</div>
		
	<div class="clear"></div>
		
	<div class="publications_list">
			
		<div class="left_head push_1 grid_3 align_right">
			<h3><span class="left_title">The New York Time</span>s</h3>
		</div>
		<div class="grid_7 push_1 publication_title"><p><a href="http://campaignstops.blogs.nytimes.com/2012/05/21/obama-and-the-new-freedom/?pagewanted=all&gwh=DFD1D8D58FB68CC35A0A2E42FF095132">Obama and the New Freedom</a><p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_author"><p>May 21, 2012</p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_description"><p>In evaluating President Barack Obama’s legislative record, historically inclined commentators frequently compare his first term to the early years of Franklin Delano Roosevelt&rsquo;s New Deal. When it comes to winning re-election, however, the commentators — and Obama — might learn something from the only Democrat besides F.D.R. to win multiple elections in the 20th century on reform platforms: Woodrow Wilson.</p></div>
						
		<div class="clear"></div>
		
		<div class="footer grid_12"></div>
		
	</div>
		
</div>

app/views/scholarish/powerwithoutvictory.html.erb
<% provide(:title, "Power Without Victory") %>
<div class="container_12">	

	<div class="clear"></div>
	
	<!-- Book Bar -->
	
	<div class="grid_10 push_1">
<!-- 			<hr id="book_spacer" /> -->
		<ul class="book_nav">
			<li><%= link_to "William James's Ethical Republic", books_path %></li>
			<li><a href="#" id="current_selection">Power Without Victory</a></li>
		</ul>
		<hr id="book_spacer" />
	</div>		
	<div class="clear"></div>

	<div class="grid_6 push_1">

		<div class="grid_6 alpha">
			<p class="buy_book"><a>Buy the Book</a></p>
		</div>

		<div class="book_title grid_6 alpha">
			<p>Power without Victory</p>
		</div>
		
		<div class="book_subhead grid_6 alpha">
			<p>Woodrow Wilson and the American Internationalist Experiment</p>
		</div>

		<div class="book_first_paragraph grid_6 alpha">
			<p>Power without Victory (now under contract with the University of Chicago Press) examines connections between philosophy, popular ideology, domestic reform, and foreign policy, providing a model of political history as cultural history.</p>
		</div>
		
		<div class="book_description grid_6 alpha">
			<p>It also complicates a narrative that for ninety years has shaped not only the government&rsquo;s role at home and abroad, but the nation&rsquo;s image in the minds of its citizens. The core of the book reinterprets the origins, content, and public reception of Wilson&rsquo;s domestic and foreign policies, culminating in a careful reconstruction of popular support for US membership in the League of Nations. In the process it recovers Wilson&rsquo;s forgotten debt to the pragmatist progressives, activist intellectuals fired by the ethical ideas of the philosopher William James. While helping Wilson lay the grounds for the American welfare state, these reformers also aided his translation of domestic progressivism into the nation&rsquo;s first genuinely internationalist foreign policy. Both developments are key to understanding American political culture in the following century, especially the ambivalence toward international institutions that to this day complicates America&rsquo;s domestic and foreign politics.</p>
			<p>Wilson&rsquo;s connection to pragmatists such as Jane Addams, W.E.B. Du Bois, Louis Brandeis, and Walter Lippmann was as complex as it was important. Though blind to the tragedy of racism in America, neglectful of political freedoms in wartime, and responsible for imperialist incursions in Latin America, Wilson drew on pragmatist ideas to develop his New Freedom reforms and, eventually, his radical vision for the postwar world. This vision was embodied in his plan for a League of Nations: a deliberative polity, requiring significant concessions of sovereignty from members, to facilitate cooperative change. Contrary to memory, support for Wilsonss vision among a majority of US interest groups was strong, and survived the disappointments of the 1919 Peace Conference. Only a stroke-impaired Wilson&rsquo;s late refusal to compromise with rivals kept the US out of the League. The emergence of a European status quo and return of American prosperity in the 1920s dissipated the urgent expectation of US League membership, but did not diminish its import: membership would have allowed more coordinated responses to the crises of the 1930s, and fostered a less domineering form of US global leadership than emerged after 1945.</p>
			<p>Methodologically, Power without Victory follows dialogues across a diverse array of intellectual, cultural, and institutional communities and actors. Drawing on archival research and a wide range of cultural-historical products, it weaves together intellectual, cultural, political, and international history, enhancing the explanatory power of each. Substantively, the book contextualizes ideas and activities whose contingent outcomes are often invoked to support agendas pursued in circumstances radically different from the past. Thus petitions to Congress, women's club annuals, and Chamber of Commerce leaflets all help demonstrate that the nation was not fated to spurn international organization in 1919-20, and that its doing so does not mean similar efforts will or must fail. The book will interest and challenge historians, political scientists, policy intellectuals, and anyone contemplating the potential for significant reform of both American and global politics</p>
		</div>

	</div>

	<div class="grid_4 push_1">

		<div class="grid_4 alpha">
			<h2 class="book_picture">William James</h2>
		</div>
	
		<div class="pull_quote grid_4 alpha">
<!-- 				<p>&ldquo;LOREM&rdquo;</p> -->
		</div>
	
		<div class="pull_quote_author grid_4 alpha">
<!-- 				<p>- LOREM</p> -->
		</div>			
	
	</div>

	<div class="footer grid_12"></div>
	
	
</div>

app/views/scholarish/publications.html.erb
<% provide(:title, "Publications") %>
<div class="container_12">	

	<div class="clear"></div>


	<!-- Sales Pitch. I think every page should have one, the publications one should reflect in greater detail what the authors write -->

	<div class="push_4 grid_7">
		<h2 class="page_title">Publications</h2>
	</div>
	
	<div class="clear"></div>
	
	<div class="publications_list">

	
		<div class="left_head push_1 grid_3 align_right">
			<h3><span class="left_title">Submitte</span>d</h3>
		</div>
		<div class="grid_7 push_1 publication_title"><p>The Fourteen Points<p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_author"><p>Trygve Throntveit</p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_description"><p>In The Oxford Encyclopedia of American Military and Diplomatic History, edited by Timothy J. Lynch. New York: Oxford University Press, Submitted.</p></div>
	
		<div class="clear"></div>
		
		<hr class="grid_7 push_4 first_category" />

		<div class="clear"></div>
		
		<div class="left_head push_1 grid_3 align_right">
			<h3><span class="left_title">In Pres</span>s</h3>
		</div>

		<div class="grid_7 push_1 publication_title"><p>The Audacity of Pragmatism: William James, Barack Obama, and the American Deliberative Tradition<p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_author"><p>Trygve Throntveit</p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_description"><p>In <span class="publications_publication_name">Revisioning William James</span>, edited by Miriam Strube. Heidelberg: Verlag Winter, In Press.</span></p></div>
		
		<div class="clear"></div>

		
		<div class="grid_7 push_4 publication_title"><p>The Higher Education of Woodrow Wilson<p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_author"><p>Trygve Throntveit</p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_description"><p>In <span class="publications_publication_name">The Educational Legacy of Woodrow Wilson: From College to Nation</span>, edited by James Axtell. Charlottesville, VA: University of Virginia Press, In Press.</span></p></div>
		
		<div class="clear"></div>

		
		<hr class="grid_7 push_4 first_category" />

		<div class="clear"></div>
		

		
		<div class="left_head push_1 grid_3 align_right">
			<h3><span class="left_title">201</span>1</h3>
		</div>

		<div class="grid_7 push_1 publication_title"><p>The Fable of the Fourteen Points: Woodrow Wilson and National Self-Determination<p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_author"><p>Trygve Throntveit</p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_description"><p><span class="publications_publication_name">Diplomatic History</span> 35, no. 3 (2011): 445-481. <a href="http://scholar.harvard.edu/throntveit/files/fable_of_the_fourteen_points_dh_35.3_june_2011.pdf">Download PDF</a></p></div>
		
		<div class="clear"></div>

		
		<div class="grid_7 push_4 publication_title"><p>A Strange Fate: Quincy Wright and the Trans-War Trajectory of Wilsonian Internationalism, 1920-1945<p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_author"><p>Trygve Throntveit</p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_description"><p><span class="publications_publication_name">White House Studies</span> 10, no. 4 (2011): 361-377. <a href="http://scholar.harvard.edu/throntveit/files/a_strange_fate_whs_10.4.pdf">Download PDF</a></p></div>
		
		<div class="clear"></div>

		<div class="grid_7 push_4 publication_title"><p>What Was Wilson Thinking? A Review of the Literature on Wilson and World Politics<p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_author"><p>Trygve Throntveit</p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_description"><p><span class="publications_publication_name">White House Studies 10</span>, no. 4 (2011): 460-474. <a href="http://scholar.harvard.edu/throntveit/files/what_was_wilson_thinking_whs_10.4.pdf">Download PDF</a></p></div>
		
		<div class="clear"></div>

		<div class="grid_7 push_4 publication_title"><p>William James's Ethical Republic<p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_author"><p>Trygve Throntveit</p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_description"><p><span class="publications_publication_name">The Journal of the History of Ideas</span> 72, no. 2 (2011): 255-277. <a href="http://scholar.harvard.edu/throntveit/files/t.throntveit_wjs_ethical_republic_jhi.72.2011.pdf">Download PDF</a></p></div>
		
		<div class="clear"></div>

		<hr class="grid_7 push_4 first_category" />

		<div class="clear"></div>
		



		<div class="left_head push_1 grid_3 align_right">
			<h3><span class="left_title">201</span>0</h3>
		</div>

		<div class="grid_7 push_1 publication_title"><p>Woodrow Wilson, Past and Present<p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_author"><p>Trygve Throntveit</p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_description"><p><span class="publications_publication_name">Democracy: A Journal of Ideas Spring</span>, no. 2010 (2010): 99-106. <a href="http://scholar.harvard.edu/throntveit/files/throntveit_cooper_review_democracy_joi.pdf">Download PDF</a></p></div>
				
		<div class="clear"></div>

		<hr class="grid_7 push_4 first_category" />

		<div class="clear"></div>
		


		<div class="left_head push_1 grid_3 align_right">
			<h3><span class="left_title">200</span>8</h3>
		</div>
			
		<div class="grid_7 push_1 publication_title"><p>"Common Counsel": Woodrow Wilson's Pragmatic Progressivism, 1885-1913<p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_author"><p>Trygve Throntveit</p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_description"><p>In <span class="publications_publication_name">Reconsidering Woodrow Wilson: Progressivism, Internationalism, War, and Peace</span>, edited by Jr. John M. Cooper, 25-56. Washington, DC/Baltimore: Wilson Center Press/Johns Hopkins University Press, 2008. <a href="http://scholar.harvard.edu/throntveit/files/throntveit_common_counsel_w._title_page.pdf">Download PDF</a></p></div>
				
		<div class="clear"></div>

		<div class="grid_7 push_4 publication_title"><p>The Will to Behold: Thorstein Veblen's Pragmatic Aesthetics<p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_author"><p>Trygve Throntveit</p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_description"><p><span class="publications_publication_name">Modern Intellectual History</span> 5, no. 3 (2008): 519-546. <a href="http://scholar.harvard.edu/throntveit/files/throntveit_will_to_behold_mih_5.3_2008.pdf">Download PDF</a></p></div>
				
		<div class="clear"></div>

		<hr class="grid_7 push_4 first_category" />

		<div class="clear"></div>
		


		<div class="left_head push_1 grid_3 align_right">
			<h3><span class="left_title">200</span>3</h3>
		</div>

		<div class="grid_7 push_1 publication_title"><p>Numbered among the Jameses: The Address at the Emerson Centenary<p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_author"><p>Trygve Throntveit</p></div>
		<div class="clear"></div>
		<div class="grid_7 push_4 publication_description"><p><span class="publications_publication_name">Streams of William James: A Newsletter of the William James Society</span> 5, no. 3 (2003): 20-25. <a href="http://scholar.harvard.edu/throntveit/files/throntveit_numbered_among_the_jameses_streams_5.3_2003.pdf">Download PDF</a></p></div>
				
		<div class="clear"></div>
		
		<div class="footer grid_12"></div>
		
	</div>
	
</div>